# to create the environment
# >>> conda env create --file environment.yml
# to register the kernel for jupyter lab:
# >>> source activate myenv
# >>> python -m ipykernel install --user --name modular_cultures --display-name "modular_cultures"

name: modular_cultures
channels:
  - conda-forge
dependencies:
  - python>=3.7
  # - anaconda
  - dask
  - dask-jobqueue
  - tqdm
  - enlighten
  - numpy
  - scipy
  - h5py
  - xarray
  - pytables
  - matplotlib
  - seaborn=0.11.2 # my violin-swarm plot hack does not work on version 0.12
  - palettable
  - networkx
  - brian2
  - cython
  - numba
  - ipywidgets
  - ipython
  - jupyter
  - jupyterlab
  - pymc
  # - theano-pymc
  - arviz
  - pip
  - pip:
    - ipy_dict_hierarchy
    - python-benedict
    - git+https://github.com/pSpitzner/bitsandbobs
